src/main/java/br/com/onlares/model/Mensagem.java
package br.com.onlares.model;

import java.io.Serializable;
import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import br.com.onlares.util.DataUtil;

/**  
* Copyright (c) 2015 GranDev - All rights reserved.
* @author Thiago Carvalho - tcarvalho@grandev.com.br
* 
*/
@Entity
@Table(name = "mensagem")
public class Mensagem implements Comparable<Mensagem>, Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@ManyToOne
	@JoinColumn(name = "usuario_id", referencedColumnName = "id")
	private Usuario usuario;
	private String assunto;
	private String texto;
	private Calendar data;
	private Calendar hora;
	private String status;
	@Transient
	private boolean visualizado;

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	public String getAssunto() {
		return assunto;
	}
	public void setAssunto(String assunto) {
		this.assunto = assunto;
	}
	public String getTexto() {
		return texto;
	}
	public void setTexto(String texto) {
		this.texto = texto;
	}
	public Calendar getData() {
		return data;
	}
	public void setData(Calendar data) {
		this.data = data;
	}
	public Calendar getHora() {
		return hora;
	}
	public void setHora(Calendar hora) {
		this.hora = hora;
	}
	public boolean isVisualizado() {
		return visualizado;
	}
	public void setVisualizado(boolean visualizado) {
		this.visualizado = visualizado;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	@Transient
	public String getDataFormatada() {
		return DataUtil.formatarData(this.data);
	}
	
	@Transient
	public String getHoraFormatada() {
		return DataUtil.formatarHora(this.hora);
	}

	@Override
	public String toString() {
		return "msg= " + id + " assnt=" + assunto;
	}
	
	@Override
	public int compareTo(Mensagem outraMensagem) {
        int mnsg = this.data.compareTo(outraMensagem.data) * -1;
        return mnsg == 0 ? this.hora.compareTo(outraMensagem.hora) * -1 : mnsg;
	}

}

src/main/java/br/com/onlares/controller/MensagemController.java
package br.com.onlares.controller;

import java.util.Collections;
import java.util.List;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Delete;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.validator.I18nMessage;
import br.com.caelum.vraptor.validator.Validator;
import br.com.onlares.dao.MensagemDao;
import br.com.onlares.dao.MoradorDao;
import br.com.onlares.model.Mensagem;

/**  
* Copyright (c) 2015 GranDev - All rights reserved.
* @author Thiago Carvalho - tcarvalho@grandev.com.br
* 
*/
@Controller
public class MensagemController {
	
	private final MensagemDao mensagemDao;
	private final MoradorDao moradorDao;
	private final Validator validator;
	private final Result result;

	@Inject
	public MensagemController(MensagemDao mensagemDao, MoradorDao moradorDao, Validator validator, Result result) {
		this.mensagemDao = mensagemDao;
		this.moradorDao = moradorDao;
		this.validator = validator;
		this.result = result;
	}
	
	public MensagemController() {
		this(null, null, null, null);
	}
	
	@Get("/mensagem/recebidas")
	public void recebidas() {
		List<Mensagem> recebidas = mensagemDao.listaRecebidas();
		Collections.sort(recebidas);
		result.include("mensagemList", recebidas);
		result.include("mensagemTotal", recebidas.size());
	}
	
	@Get("/mensagem/enviadas")
	public void enviadas() {
		List<Mensagem> enviadas = mensagemDao.listaEnviadas();
		Collections.sort(enviadas);
		result.include("mensagemList", enviadas);
		result.include("mensagemTotal", enviadas.size());
	}
	
	@Get("/mensagem/visualizaRecebida/{id}")
	public void visualizaRecebida(Long id) {
		Mensagem mensagem = mensagemDao.buscaRecebida(id);
		if (mensagem == null) {
			result.notFound();
		} else {
			if (!mensagemDao.foiVisualizado(id)) {
				mensagemDao.setaVisualizacao(id);
				mensagem.setVisualizado(true);
			}
			result.include("mensagem", mensagem);
		}
	}
	
	@Get("/mensagem/visualizaEnviada/{id}")
	public void visualizaEnviada(Long id) {
		Mensagem mensagem = mensagemDao.buscaEnviada(id);
		if (mensagem == null) {
			result.notFound();
		} else {
			result.include("mensagem", mensagem);
			result.include("destinatarios", mensagemDao.buscaDestinatarios(mensagem));
		}
	}
	
	@Get("/mensagem/novo")
	public void novo() {
		result.include("moradorList", moradorDao.listaRegistrados());
	}
	
	@Post("/mensagem/")
	public void envia(Mensagem mensagem, List<Long> destinatarios) {
        if (checkNull(mensagem.getAssunto()).equals("")) {
   			validator.add(new I18nMessage("mensagem.envia", "campo.obrigatorio", "Assunto"));
   		}
        if (checkNull(mensagem.getTexto()).equals("")) {
   			validator.add(new I18nMessage("mensagem.envia", "campo.obrigatorio", "Texto"));
   		}
        
		validator.onErrorUsePageOf(this).novo();
		
		mensagemDao.envia(mensagem, destinatarios);
		result.include("notice", "Mensagem enviada com sucesso!");
		result.redirectTo(this).enviadas();
	}
	
	@Delete("/mensagem/removeRecebidas/")
	public void removeRecebidas(List<Long> mensagens, HttpServletRequest request){
		mensagemDao.removeRecebidas(mensagens);
		result.redirectTo(this).recebidas();
	}
	
	@Delete("/mensagem/removeEnviadas/")
	public void removeEnviadas(List<Long> mensagens, HttpServletRequest request){
		mensagemDao.removeEnviadas(mensagens);
		result.redirectTo(this).enviadas();
	}
	
	private String checkNull(String value) {
		if (value == null) {
			return ("");
		} else {
			return (value.trim());
		}
	}
	
}

src/main/webapp/WEB-INF/jsp/mensagem/enviadas.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="/templates/jstl.jsp" %>

<!DOCTYPE html>
<html>

<head>
	<meta name="description" content="" />
	<!-- page specific plugin styles -->
</head>

<body>

<div class="main-content-inner">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="${ctx}/admin/index">Home</a>
			</li>

			<li class="active">Mensagens</li>
		</ul><!-- /.breadcrumb -->
		
	</div>

	<div class="page-content">
	
		<%@ include file="/templates/messages.jsp"%>
		
		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				
				<div class="page-header">
					<h1>
						Enviadas
					</h1>
				</div><!-- /.page-header -->
				
				<div class="row">
					<div class="col-xs-12">
						<div class="tabbable">
							<ul id="inbox-tabs" class="inbox-tabs nav nav-tabs padding-16 tab-size-bigger tab-space-1">
								<li class="li-new-mail pull-right">
									<a href="${linkTo[MensagemController].novo()}" data-target="write" class="btn-new-mail">
										<span class="btn btn-success no-border">
											<i class="ace-icon fa fa-envelope bigger-130"></i>
											<span class="bigger-110">Nova Mensagem</span>
										</span>
									</a>
								</li><!-- /.li-new-mail -->

								<li>
									<a href="${linkTo[MensagemController].recebidas()}" data-target="inbox">
										<i class="blue ace-icon fa fa-inbox bigger-130"></i>
										<span class="bigger-110">Recebidas</span>
									</a>
								</li>

								<li class="active">
									<a href="${linkTo[MensagemController].enviadas()}" data-target="sent">
										<i class="orange ace-icon fa fa-location-arrow bigger-130"></i>
										<span class="bigger-110">Enviadas</span>
									</a>
								</li>
							</ul>

							<div class="tab-content no-border no-padding">
								<div id="inbox" class="tab-pane in active">
									<div class="message-container">
									<form id="myform" class="form-horizontal message-form col-xs-12" action="${ctx}/mensagem/removeEnviadas/" method="post" >
										<div id="id-message-list-navbar" class="message-navbar clearfix">
											<div class="message-bar">
												<div class="message-toolbar hide">
													<div class="inline position-relative align-left">
													</div>
													<button name="_method" value="DELETE" class="btn btn-sm btn-danger no-border ">
														<i class="ace-icon fa fa-trash-o bigger-125"></i>
														<span class="bigger-110">Deletar</span>
													</button>
												</div>
											</div>

											<div>
												<div class="messagebar-item-left">
													<label class="inline middle">
														<input type="checkbox" id="id-toggle-all" class="ace" />
														<span class="lbl"></span>
													</label>
												</div>

												<div class="messagebar-item-right">
													<div class="inline position-relative">
													</div>
												</div>

												<div class="nav-search minimized">
												</div>
											</div>
										</div>
										<div class="message-list-container">
											<div class="message-list" id="message-list">
											<c:choose>
												<c:when test="${mensagemList.isEmpty()}">
													<h3>Sem mensagens</h3>
												</c:when>
												<c:otherwise>
													<c:forEach items="${mensagemList}" var="mensagem" >
														<div class="message-item">
															<label class="inline">
																<input type="checkbox" class="ace" name="mensagens[]" value="${mensagem.id}" /> 
																<span class="lbl"></span>
															</label>
															<a href="${linkTo[MensagemController].visualizaEnviada(mensagem.id)}" data-target="inbox">
																<span class="sender">Eu</span>
																<span class="data">${mensagem.dataFormatada}</span>
			
																<span class="summary">
																	<span class="text">
																		${mensagem.assunto}
																	</span>
																</span>
															</a>
														</div>
														</c:forEach>
												</c:otherwise>
											</c:choose>
											</div>
										</div>
										<div class="message-footer clearfix">
											<div class="pull-left"> ${mensagemTotal} mensagens do total </div>

											<div class="pull-right">
											</div>
										</div>
										</form>
									</div>
								</div>
							</div><!-- /.tab-content -->
						</div><!-- /.tabbable -->
					</div><!-- /.col -->
				</div><!-- /.row -->
				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div>

<content tag="local_script">
	<!-- page specific plugin scripts -->
		
	<!-- inline scripts related to this page -->
	<script type="text/javascript">
		jQuery(function($){
			$("#myform").submit(function() {
			   // Retrieve the HTML from the plugin
			   var html = $('#editor1').html();
			   // Put this in the hidden field
			   $("#html").val(html);
			});
		
			//basic initializations
			$('.message-list .message-item input[type=checkbox]').removeAttr('checked');
			$('.message-list').on('click', '.message-item input[type=checkbox]' , function() {
				$(this).closest('.message-item').toggleClass('selected');
				if(this.checked) Inbox.display_bar(1);//display action toolbar when a message is selected
				else {
					Inbox.display_bar($('.message-list input[type=checkbox]:checked').length);
					//determine number of selected messages and display/hide action toolbar accordingly
				}		
			});
			
			//check/uncheck all messages
			$('#id-toggle-all').removeAttr('checked').on('click', function(){
				if(this.checked) {
					Inbox.select_all();
				} else Inbox.select_none();
			});
			
			//select all
			$('#id-select-message-all').on('click', function(e) {
				e.preventDefault();
				Inbox.select_all();
			});
			
			//select none
			$('#id-select-message-none').on('click', function(e) {
				e.preventDefault();
				Inbox.select_none();
			});
			
			/////////
		
			//display first message in a new area
			$('.message-list .message-item:eq(0) .text').on('click', function() {
				//show the loading icon
				$('.message-container').append('<div class="message-loading-overlay"><i class="fa-spin ace-icon fa fa-spinner orange2 bigger-160"></i></div>');
				
				$('.message-inline-open').removeClass('message-inline-open').find('.message-content').remove();
			});
		
			var Inbox = {
				//displays a toolbar according to the number of selected messages
				display_bar : function (count) {
					if(count == 0) {
						$('#id-toggle-all').removeAttr('checked');
						$('#id-message-list-navbar .message-toolbar').addClass('hide');
						$('#id-message-list-navbar .message-infobar').removeClass('hide');
					}
					else {
						$('#id-message-list-navbar .message-infobar').addClass('hide');
						$('#id-message-list-navbar .message-toolbar').removeClass('hide');
					}
				}
				,
				select_all : function() {
					var count = 0;
					$('.message-item input[type=checkbox]').each(function(){
						this.checked = true;
						$(this).closest('.message-item').addClass('selected');
						count++;
					});
					
					$('#id-toggle-all').get(0).checked = true;
					
					Inbox.display_bar(count);
				}
				,
				select_none : function() {
					$('.message-item input[type=checkbox]').removeAttr('checked').closest('.message-item').removeClass('selected');
					$('#id-toggle-all').get(0).checked = false;
					
					Inbox.display_bar(0);
				}
			}
		
		});
	</script>
	
	<!-- confirm script -->
	<script type="text/javascript">
		$( "#myform").submit(function(event) {
			if (!confirm('Você realmente deseja exlucir essas mensagens?')){
			  event.preventDefault();
			}
		});
	</script>
	
	<!-- menu script -->
	<script type="text/javascript">
		$('li').click(function(e) {
			$('li').removeClass('active');
	        $(this).addClass('active');
	    });
	
		$(function() {
			$('#menu_mensagens').addClass('active');
		});
	</script>
</content>

</body>

</html>

src/main/webapp/WEB-INF/jsp/mensagem/visualizaEnviada.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="/templates/jstl.jsp" %>

<!DOCTYPE html>
<html>

<head>
	<meta name="description" content="" />
	<!-- page specific plugin styles -->
</head>

<body>

<div class="main-content-inner">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="${ctx}/admin/index">Home</a>
			</li>

			<li class="active">Mensagens</li>
		</ul><!-- /.breadcrumb -->
		
	</div>

	<div class="page-content">
	
		<%@ include file="/templates/messages.jsp"%>
		
		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				
				<div class="page-header">
					<h1>
						Enviada
					</h1>
				</div><!-- /.page-header -->
				
				<div class="row">
					<div class="col-xs-12">
						<div class="tabbable">
							<ul id="inbox-tabs" class="inbox-tabs nav nav-tabs padding-16 tab-size-bigger tab-space-1">
								<li class="li-new-mail pull-right">
									<a href="${linkTo[MensagemController].novo()}" data-target="write" class="btn-new-mail">
										<span class="btn btn-success no-border">
											<i class="ace-icon fa fa-envelope bigger-130"></i>
											<span class="bigger-110">Nova Mensagem</span>
										</span>
									</a>
								</li><!-- /.li-new-mail -->

								<li>
									<a href="${linkTo[MensagemController].recebidas()}" data-target="inbox">
										<i class="blue ace-icon fa fa-inbox bigger-130"></i>
										<span class="bigger-110">Recebidas</span>
									</a>
								</li>

								<li>
									<a href="${linkTo[MensagemController].enviadas()}" data-target="sent">
										<i class="orange ace-icon fa fa-location-arrow bigger-130"></i>
										<span class="bigger-110">Enviadas</span>
									</a>
								</li>
							</ul>

							<div class="tab-content no-border no-padding">
								<div id="inbox" class="tab-pane in active">
									<div class="message-container">
										<div id="id-message-item-navbar" class="message-navbar clearfix">
											<div class="message-bar">
											</div>

											<div>
												<div class="messagebar-item-left">
													<a href="${linkTo[MensagemController].enviadas()}">
														<i class="ace-icon fa fa-arrow-left blue bigger-110 middle"></i>
														<b class="bigger-110 middle">Voltar</b>
													</a>
												</div>

												<div class="messagebar-item-right">
													<i class="ace-icon fa fa-clock-o bigger-110 orange"></i>
													<span class="grey">${mensagem.dataFormatada}, ${mensagem.horaFormatada}</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div><!-- /.tab-content -->
						</div><!-- /.tabbable -->
					</div><!-- /.col -->
				</div><!-- /.row -->

				<div class="message-content" id="id-message-content">
					<div class="message-header clearfix">
						<div class="pull-left">
							Assunto: 
							<span class="blue bigger-125"> ${mensagem.assunto} </span>

							<div class="space-4"></div>

							&nbsp;
							Para: 
							<c:forEach items="${destinatarios}" var="usuario">
								<a href="${linkTo[PerfilController].visualiza(usuario.id)}" class="sender">${usuario.nome}</a>; 
							</c:forEach>
						</div>
					</div>

					<div class="hr hr-double"></div>

					<div class="message-body">
						${mensagem.texto}
					</div>

					<div class="hr hr-double"></div>
				</div><!-- /.message-content -->
				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div>

<content tag="local_script">
	<!-- page specific plugin scripts -->
		
	<!-- inline scripts related to this page -->
		
	<!-- menu script -->
	<script type="text/javascript">
		$('li').click(function(e) {
			$('li').removeClass('active');
	        $(this).addClass('active');
	    });
	
		$(function() {
			$('#menu_mensagens').addClass('active');
		});
	</script>
</content>

</body>

</html>

src/main/webapp/WEB-INF/jsp/mensagem/visualizaRecebida.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="/templates/jstl.jsp" %>

<!DOCTYPE html>
<html>

<head>
	<meta name="description" content="" />
	<!-- page specific plugin styles -->
</head>

<body>

<div class="main-content-inner">
	<div class="breadcrumbs" id="breadcrumbs">
		<script type="text/javascript">
			try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
		</script>

		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="${ctx}/admin/index">Home</a>
			</li>

			<li class="active">Mensagens</li>
		</ul><!-- /.breadcrumb -->
		
	</div>

	<div class="page-content">
	
		<%@ include file="/templates/messages.jsp"%>
		
		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				
				<div class="page-header">
					<h1>
						Recebida
					</h1>
				</div><!-- /.page-header -->
				
				<div class="row">
					<div class="col-xs-12">
						<div class="tabbable">
							<ul id="inbox-tabs" class="inbox-tabs nav nav-tabs padding-16 tab-size-bigger tab-space-1">
								<li class="li-new-mail pull-right">
									<a href="${linkTo[MensagemController].novo()}" data-target="write" class="btn-new-mail">
										<span class="btn btn-success no-border">
											<i class="ace-icon fa fa-envelope bigger-130"></i>
											<span class="bigger-110">Nova Mensagem</span>
										</span>
									</a>
								</li><!-- /.li-new-mail -->

								<li>
									<a href="${linkTo[MensagemController].recebidas()}" data-target="inbox">
										<i class="blue ace-icon fa fa-inbox bigger-130"></i>
										<span class="bigger-110">Recebidas</span>
									</a>
								</li>

								<li>
									<a href="${linkTo[MensagemController].enviadas()}" data-target="sent">
										<i class="orange ace-icon fa fa-location-arrow bigger-130"></i>
										<span class="bigger-110">Enviadas</span>
									</a>
								</li>
							</ul>

							<div class="tab-content no-border no-padding">
								<div id="inbox" class="tab-pane in active">
									<div class="message-container">
										<div id="id-message-item-navbar" class="message-navbar clearfix">
											<div class="message-bar">
											</div>

											<div>
												<div class="messagebar-item-left">
													<a href="${linkTo[MensagemController].recebidas()}">
														<i class="ace-icon fa fa-arrow-left blue bigger-110 middle"></i>
														<b class="bigger-110 middle">Voltar</b>
													</a>
												</div>

												<div class="messagebar-item-right">
													<i class="ace-icon fa fa-clock-o bigger-110 orange"></i>
													<span class="grey">${mensagem.dataFormatada}, ${mensagem.horaFormatada}</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div><!-- /.tab-content -->
						</div><!-- /.tabbable -->
					</div><!-- /.col -->
				</div><!-- /.row -->

				<div class="message-content" id="id-message-content">
					<div class="message-header clearfix">
						<div class="pull-left">
							Assunto: 
							<span class="blue bigger-125"> ${mensagem.assunto} </span>

							<div class="space-4"></div>
							
							&nbsp;
							De: <a href="${linkTo[PerfilController].visualiza(mensagem.usuario.id)}" class="sender">${mensagem.usuario.nome}</a>
						</div>
					</div>

					<div class="hr hr-double"></div>

					<div class="message-body">
						${mensagem.texto}
					</div>

					<div class="hr hr-double"></div>
				</div><!-- /.message-content -->
				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
</div>

<content tag="local_script">
	<!-- page specific plugin scripts -->
		
	<!-- inline scripts related to this page -->
		
	<!-- menu script -->
	<script type="text/javascript">
		$('li').click(function(e) {
			$('li').removeClass('active');
	        $(this).addClass('active');
	    });
	
		$(function() {
			$('#menu_mensagens').addClass('active');
		});
	</script>
</content>

</body>

</html>